# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: magic_eraser.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'magic_eraser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12magic_eraser.proto\x12\x0bmagiceraser\"~\n\x0eProcessRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x12\n\ncolor_type\x18\x02 \x01(\t\x12\x13\n\x0b\x66ill_method\x18\x03 \x01(\t\x12\x0f\n\x07\x65nhance\x18\x04 \x01(\x08\x12\x0e\n\x06\x64\x65skew\x18\x05 \x01(\x08\x12\x0e\n\x06whiten\x18\x06 \x01(\x08\"M\n\x0fProcessResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magic_eraser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSREQUEST']._serialized_start=35
  _globals['_PROCESSREQUEST']._serialized_end=161
  _globals['_PROCESSRESPONSE']._serialized_start=163
  _globals['_PROCESSRESPONSE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
